apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hpong
  annotations:
    github.com/project-slug: illuher/hpong
spec:
  type: other
  lifecycle: experimental
  owner: illuher
  system: examples
  namespace: default
  tags:
    - golang
    - http
  links:
    - title: Website
      url: http://google.com
      
