apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hpong
  name: hpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpong
  template:
    metadata:
      labels:
        app: hpong
    spec:
      containers:
      - image: illuher/hpong:0.0.3-scratch
        name: hpong
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "0.1"
            memory: "50M"
          requests:
            memory: "50M"
